sonar.projectKey=CamilaGutierrezCasas-ing_Proyecto_Grado-ClasificadorDeCorreosElectronicosA-aniendoChatbot
sonar.organization=camilagutierrezcasas-ing

sonar.sources=backend_base,correo-frontend
sonar.python.version=3.13
